# Generated by Django 5.0.2 on 2024-02-21 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
